# Site settings
title: Simon van der Veldt
baseurl: ""
url: "http://simonvanderveldt.nl"
author: Simon van der Veldt
permalink: /:title
include: ["_pages"]
exclude: ["vendor"]

# Build settings
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["footnotes", "smart", "hard_wrap", "no_intra_emphasis"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
